# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Adjust this to the version you're using


    # Build for x64 architecture
    - name: Restore NuGet Packages for x64
      run: dotnet restore --runtime win-x64

    - name: Build x64
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishAot=true
      continue-on-error: false

    - name: Package x64 Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: x64ReleaseArtifacts
        path: publish
        overwrite: true


    # Build for arm64 architecture
    - name: Restore NuGet Packages for arm64
      run: dotnet restore --runtime win-arm64

    - name: Build arm64
      run: dotnet publish -c Release -r win-arm64 --self-contained true /p:PublishAot=true
      continue-on-error: false

    - name: Package arm64 Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: arm64ReleaseArtifacts
        path: publish
        overwrite: true
